### ISSUE TITLE
Error: "Feature 'VectorSearch' is not available in this edition. (10005)" when trying to put data in the box

### ISSUE THREAD

**Issue by spassky1** [objectbox/objectbox-swift-spm#1]
Hello, I don't know if this package is ready for use yet. However, when i try to put data to the box, I counter "Error occurred: Feature 'VectorSearch' is not available in this edition. (10005)". It seems like the VectorSearch feature is not enabled or available in the current edition. Could you please provide guidance on how to resolve this issue or enable the VectorSearch feature? Is this issue related to the edition of ObjectBox?

Environment:
-Xcode Version: 16
-ObjectBox Version: 4.1.0-beta.1
-MacOS Sequoia 15.1

**Comment by greenrobot-team** [comment]
Thanks for reporting! Published a new preview release (`4.1.0-beta.2`) that resolves this.
